remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Gerlinde Theunissen
description:  Polisci Ph.D. student at UniKonstanz/ EXCInequality; Currently at UCSanDiego: My work relates to contexts, neighborhood interactions + exposure, and spatial analyses of political behavior. 
